# Generated by Django 5.2.17 on 2026-09-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_course_id_alter_student_id_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='jornada',
            field=models.CharField(choices=[('D', 'Diurna'), ('V', 'Vespertina')], default='D', max_length=1, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='student',
            name='jornada',
            field=models.CharField(choices=[('D', 'Diurna'), ('V', 'Vespertina')], default='D', max_length=1, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='student',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
