# Generated by Django 5.2.17 on 2026-09-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_course_jornada_student_jornada_student_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
