# Generated by Django 5.2.17 on 2026-09-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_teacher_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creditos', models.PositiveSmallIntegerField(default=0, verbose_name='Créditos')),
                ('tipo', models.CharField(choices=[('O', 'Obligatoria'), ('E', 'Electiva')], default='O', max_length=1, verbose_name='Tipo')),
                ('nivel', models.CharField(choices=[('1', 'Primer año'), ('2', 'Segundo año'), ('3', 'Tercer año'), ('4', 'Cuarto año'), ('5', 'Quinto año')], default='1', max_length=1, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignatura',
                'ordering': ['nombre'],
            },
        ),
    ]
