# Generated by Django 5.2.17 on 2026-09-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_asignatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['codigo'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='course',
            name='codigo',
            field=models.CharField(default='SIN-CODIGO', help_text='Ej: IEC-N4-C2 (Carrera-Nivel-Grupo)', max_length=20, unique=True, verbose_name='Codigo de seccion'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre descriptivo de la seccion (opcional)', max_length=100, verbose_name='Descripcion'),
        ),
    ]
